/*
 * opt_compat_mach.h — module-local option header.
 *
 * COMPAT_MACH is this module's own option, hard-on for any build of
 * mach.ko. The Makefile also passes -DCOMPAT_MACH on CFLAGS; both
 * routes set the same flag so includes that test either compile path
 * agree.
 *
 * Not generated by any kernel config; not overridden by KERNBUILDDIR.
 * Shipped verbatim with the source.
 */

#define COMPAT_MACH 1
